-- CreateTable
CREATE TABLE "TeamStats" (
    "teamNumber" INTEGER NOT NULL,
    "nickname" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "stateProvince" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "district" TEXT NOT NULL,
    "seedOrigin" TEXT NOT NULL,
    "qualificationMatchesPlayed" INTEGER NOT NULL,
    "qualWins" INTEGER NOT NULL,
    "qualLosses" INTEGER NOT NULL,
    "qualTies" INTEGER NOT NULL,
    "cargoBonusRPs" INTEGER NOT NULL,
    "hangarBonusRPs" INTEGER NOT NULL,
    "totalMatchesPlayed" INTEGER NOT NULL,
    "dQMatches" INTEGER NOT NULL,
    "surrogateMatches" INTEGER NOT NULL,
    "totalWins" INTEGER NOT NULL,
    "totalLosses" INTEGER NOT NULL,
    "totalTies" INTEGER NOT NULL,
    "winningMarginElo" DOUBLE PRECISION NOT NULL,
    "totalPoints" DOUBLE PRECISION NOT NULL,
    "unpenalizedTotalPoints" DOUBLE PRECISION NOT NULL,
    "winningMargin" DOUBLE PRECISION NOT NULL,
    "win" DOUBLE PRECISION NOT NULL,
    "rankingPoints" DOUBLE PRECISION NOT NULL,
    "autoPoints" DOUBLE PRECISION NOT NULL,
    "teleopExcludingEndgamePoints" DOUBLE PRECISION NOT NULL,
    "endgamePoints" DOUBLE PRECISION NOT NULL,
    "totalScoredCargo" DOUBLE PRECISION NOT NULL,
    "cargoBonusRPILS" DOUBLE PRECISION NOT NULL,
    "hangarBonusRPILS" DOUBLE PRECISION NOT NULL,
    "autoTaxiPoints" DOUBLE PRECISION NOT NULL,
    "autoTaxiRate" DOUBLE PRECISION NOT NULL,
    "autoCargoPoints" DOUBLE PRECISION NOT NULL,
    "autoCargoLower" DOUBLE PRECISION NOT NULL,
    "autoCargoUpper" DOUBLE PRECISION NOT NULL,
    "autoCargoTotal" DOUBLE PRECISION NOT NULL,
    "quintetAchieved" DOUBLE PRECISION NOT NULL,
    "quintetAchievedRate" DOUBLE PRECISION NOT NULL,
    "teleopCargoPoints" DOUBLE PRECISION NOT NULL,
    "teleopCargoLower" DOUBLE PRECISION NOT NULL,
    "teleopCargoUpper" DOUBLE PRECISION NOT NULL,
    "teleopCargoTotal" DOUBLE PRECISION NOT NULL,
    "endgameLowPoints" DOUBLE PRECISION NOT NULL,
    "atLeastLowEndgameRate" DOUBLE PRECISION NOT NULL,
    "endgameMidPoints" DOUBLE PRECISION NOT NULL,
    "atLeastMidEndgameRate" DOUBLE PRECISION NOT NULL,
    "endgameHighPoints" DOUBLE PRECISION NOT NULL,
    "atLeastEndgameHighRate" DOUBLE PRECISION NOT NULL,
    "endgameTraversalPoints" DOUBLE PRECISION NOT NULL,
    "endgameTraversalRate" DOUBLE PRECISION NOT NULL,
    "cargoBonus" DOUBLE PRECISION NOT NULL,
    "cargoBonusCompletionPercentage" DOUBLE PRECISION NOT NULL,
    "cargoBonusContributingCargo" DOUBLE PRECISION NOT NULL,
    "hangarBonus" DOUBLE PRECISION NOT NULL,
    "hangarBonusCompletionPercentage" DOUBLE PRECISION NOT NULL,
    "foulCount" DOUBLE PRECISION NOT NULL,
    "techFoulCount" DOUBLE PRECISION NOT NULL,
    "foulPoints" DOUBLE PRECISION NOT NULL,
    "foulsDrawn" DOUBLE PRECISION NOT NULL,
    "techFoulsDrawn" DOUBLE PRECISION NOT NULL,
    "foulPointsDrawn" DOUBLE PRECISION NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "TeamStats_teamNumber_key" ON "TeamStats"("teamNumber");

-- AddForeignKey
ALTER TABLE "TeamStats" ADD CONSTRAINT "TeamStats_teamNumber_fkey" FOREIGN KEY ("teamNumber") REFERENCES "Team"("teamNumber") ON DELETE RESTRICT ON UPDATE CASCADE;
